# Generated by Django 4.0.4 on 2024-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_alter_users_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='certificate',
            field=models.ImageField(upload_to=''),
        ),
    ]
