# Generated by Django 4.0.4 on 2024-02-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_alter_result_details_analysis_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicanalyses',
            name='its_derivatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='patientapp.basicanalyses'),
        ),
    ]
